title: Ons eigen teststraat
description: "Deze website is een testomgeving voor ons om writeups op te publiceren, om uit te vinden wat voor ons het fijnste werkt en om te zien of het überhaupt iets voor ons is."
email: "StabyHacker@gmail.com"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

